export { default as Main } from "./main"
export { default as Nav } from "./nav"
export { default as Theme } from "./theme"
export { default as GlobalStyle } from "./GlobalStyle"
export { default as Header } from "./header"
export { default as Section } from "./section"
export { default as Fonts } from "./fonts"
