export { default as AboutMe } from "./aboutMe"
export { default as Intro } from "./intro"
export { default as WorkExperience } from "./workExperience"
export { default as Projects } from "./projects"
export { default as Contact } from "./contact"
